<div class="Title2"> Online Bill Payment </div>


<div id="contentBox">
<form>                            
    <table border="0" cellspacing="0" cellpadding="0" width="570" class="commonForm2">
            <tbody><tr class="LightGrey">
        <td class="label" width="30%">Payee:</td>
        <td>
             <select id="payeeList">
                <option value="0101HOST">0101HOST</option>
                <option value="1579">1579</option>
                <option value="1628">1628</option>
                <option value="3TTRAVEL.COM">3TTRAVEL.COM</option>
                <option value="ABCPATHWAYSSCHOOL">ABC PATHWAYS SCHOOL</option>
                <option value="ABERDEENKAI-FONGWELFAREASSO">ABERDEEN KAI-FONG WELFARE ASSO</option>
                <option value="AC&amp;amp;A">AC&amp;A</option>
                <option value="ACCESSYOU.COM">ACCESSYOU.COM</option>
                <option value="ACELIFEINSURANCECOLTD">ACE LIFE INSURANCE CO LTD</option>
                <option value="ADVENTURECOUNSELLINGASSLTD">ADVENTURE COUNSELLING ASS LTD</option>
                <option value="AGEASINSURANCECO(ASIA)LTD">AGEAS INSURANCE CO (ASIA) LTD</option>
                <option value="AIAINTERNATIONALLIMITED">AIA INTERNATIONAL LIMITED</option>
                <option value="AIAMPFSERVICES">AIA MPF SERVICES</option>
                <option value="ALLIANCEPSCHKLNTONG">ALLIANCE P SCH KLN TONG</option>
                <option value="ALLIANCEPRISCHOOLSHEUNGSHUI">ALLIANCE PRI SCHOOL SHEUNGSHUI</option>
                <option value="ALLIANCEPRIMARYSCHOOLWHAMPO">ALLIANCE PRIMARY SCHOOL WHAMPO</option>
                <option value="AMOYGARDENS">AMOY GARDENS</option>
                <option value="APPLESTORAGE">APPLE STORAGE</option>
                <option value="ASIAPACIFIC'SLUNCHEONSTAR">ASIA PACIFIC'S LUNCHEON STAR</option>
                <option value="ASIATRAVELCARECOLTD">ASIA TRAVEL CARE CO LTD</option>
                <option value="ASSOOFEVANGLFREECHRS,THE">ASSO OF EVANGL FREE CHRS, THE</option>
                <option value="AUSINOFOODLIMITED">AUSINO FOOD LIMITED</option>
                <option value="AUTOMATEDSYSTEMS(HK)LTD">AUTOMATED SYSTEMS (HK) LTD</option>
                <option value="AUTOTOLL">AUTOTOLL</option>
                <option value="AXA">AXA</option>
                <option value="AXAWEALTHMGT(HK)LTD">AXA WEALTH MGT (HK) LTD</option>
                <option value="BANNERSHOP">BANNERSHOP</option>
                <option value="BAPTIST(STW)LUIMINGCHOIPS">BAPTIST (STW) LUIMINGCHOI P S</option>
                <option value="BAPTISTLUIMINGCHOIPRISCH">BAPTIST LUI MING CHOI PRI SCH</option>
                <option value="BAPTISTLUIMINGCHOISECSCH">BAPTIST LUI MING CHOI SEC SCH</option>
                <option value="BAPTISTOIKWANSOCSVC">BAPTIST OI KWAN SOC SVC</option>
                <option value="BAPTISTWINGLUNGSECSCHOOL">BAPTIST WING LUNG SEC SCHOOL</option>
                <option value="BAYLEY&amp;amp;JACKSONDENTALSURL">BAYLEY &amp; JACKSON DENTAL SUR L</option>
                <option value="BCT(MPF)INDUSTRYCHOICE">BCT (MPF) INDUSTRY CHOICE</option>
                <option value="BCT(MPF)PROCHOICE">BCT (MPF) PRO CHOICE</option>
                <option value="BEALIFELIMITED">BEA LIFE LIMITED</option>
                <option value="BEECRAZY">BEECRAZY</option>
                <option value="BEVERLYHILL(ESTATEMGT)LTD">BEVERLY HILL (ESTATE MGT) LTD</option>
                <option value="BIGLINEHOLIDAYLTD">BIG LINE HOLIDAY LTD</option>
                <option value="BIOCYCLE(HONGKONG)LIMITED">BIOCYCLE (HONG KONG) LIMITED</option>
                <option value="BISHOPWALSHPRIMARYSCHOOL">BISHOP WALSH PRIMARY SCHOOL</option>
                <option value="BLUECROSS(ASIA-PACIFIC)INSL">BLUE CROSS (ASIA-PACIFIC)INS L</option>
                <option value="BMWCONCESSIONAIRES(HK)LTD">BMW CONCESSIONAIRES (HK) LTD</option>
                <option value="BOCGROUPLIFEASSURCOLTD">BOC GROUP LIFE ASSUR CO LTD</option>
                <option value="BOYS'ANDGIRLS'CLUBS,THE">BOYS' AND GIRLS' CLUBS, THE</option>
                <option value="BOYS'BRIGADE,HONGKONG,THE">BOYS' BRIGADE, HONG KONG, THE</option>
                <option value="BRITISHCOUNCIL">BRITISH COUNCIL</option>
                <option value="BROADENLEISUREOUTLETSCOLTD">BROADEN LEISURE OUTLETS CO LTD</option>
                <option value="BROADWAY-NASSAUINVLTD">BROADWAY-NASSAU INV LTD</option>
                <option value="BSHHOMEAPPLIANCESLIMITED">BSH HOME APPLIANCES LIMITED</option>
                <option value="BUDDHISTCHIKINGPRISCHOOL">BUDDHIST CHI KING PRI SCHOOL</option>
                <option value="BUDDHISTSINTAKCOLLEGE">BUDDHIST SIN TAK COLLEGE</option>
                <option value="BUDDHISTTAIHUNGCOLLEGE">BUDDHIST TAI HUNG COLLEGE</option>
                <option value="BUDDHISTWONGFUNGLINGCOLLEG">BUDDHIST WONG FUNG LING COLLEG</option>
                <option value="BUNTANGBUSSERVICECOLTD">BUN TANG BUS SERVICE CO LTD</option>
                <option value="BUPA(ASIA)LTD">BUPA (ASIA) LTD</option>
                <option value="BUSINESSCENTRE(HK)">BUSINESS CENTRE (HK)</option>
                <option value="C&amp;amp;MALLIANCESUNKEISECSCH">C &amp; M ALLIANCE SUN KEI SEC SCH</option>
                <option value="CALAMFSECSCHOOL">C A LAM F SEC SCHOOL</option>
                <option value="C&amp;amp;MACHURCHUNIONHK">C&amp;MA CHURCH UNION HK</option>
                <option value="C.A.T.S.H.C.PRISCHOOL">C. A. T. S. H. C. PRI SCHOOL</option>
                <option value="C.P.C.YAODAOPRIMARYSCHOOL">C.P.C. YAO DAO PRIMARY SCHOOL</option>
                <option value="CABLETV&amp;amp;I-CABLE">CABLE TV &amp; I-CABLE</option>
                <option value="CAGLTD">CAG LTD</option>
                <option value="CALTEXSTARCARD">CALTEX STARCARD</option>
                <option value="CANADIANINT'LSCHOOLOFHK">CANADIAN INT'L SCHOOL OF HK</option>
                <option value="CANOSSAPRIMARYSCHOOL">CANOSSA PRIMARY SCHOOL</option>
                <option value="CANOSSAPRIMARYSCHOOL(SPK)">CANOSSA PRIMARY SCHOOL (SPK)</option>
                <option value="CANOSSASCHOOL(HK)">CANOSSA SCHOOL (HK)</option>
                <option value="CARITAS-HONGKONG">CARITAS - HONG KONG</option>
                <option value="CARITASCHARLESVATHCOLLEGE">CARITAS CHARLES VATH COLLEGE</option>
                <option value="CARITASTUENMUNMARDENFSS">CARITAS TUEN MUN MARDEN F S S</option>
                <option value="CATHOLICMISSIONSCHOOL">CATHOLIC MISSION SCHOOL</option>
                <option value="CAYLEY-CAVHEIPH2BLK8">CAYLEY - CAV HEI PH2 BLK 8</option>
                <option value="CAYLEY-EASTERNCENTRE">CAYLEY - EASTERN CENTRE</option>
                <option value="CAYLEY-FULLVIEWCOURT">CAYLEY - FULLVIEW COURT</option>
                <option value="CAYLEY-KOWAYCOURT">CAYLEY - KOWAY COURT</option>
                <option value="CAYLEY-SMITHFIELDCOURT">CAYLEY - SMITHFIELD COURT</option>
                <option value="CAYLEY-TSZONCOURT">CAYLEY - TSZ ON COURT</option>
                <option value="CAYLEY-SOUTHEASTINDBUILDING">CAYLEY -SOUTHEAST IND BUILDING</option>
                <option value="CAYLEYPROPMAN-BELGDNPH1">CAYLEY PROP MAN - BEL GDN PH 1</option>
                <option value="CAYLEY-CITYGARDEN">CAYLEY-CITY GARDEN</option>
                <option value="CAYLEY-EASTERNPLAZA">CAYLEY-EASTERN PLAZA</option>
                <option value="CAYLEYPMLTD-YARDLEYCOMMBLDG">CAYLEYPM LTD - YARDLEYCOMMBLDG</option>
                <option value="CCCCHUENYUENSECONDPRISCH">CCC CHUEN YUEN SECOND PRI SCH</option>
                <option value="CCCCHUNKWONGPRIMARYSCHOOL">CCC CHUN KWONG PRIMARY SCHOOL</option>
                <option value="CCCHEEPWOHCOLLEGE">CCC HEEP WOH COLLEGE</option>
                <option value="CCCKEICHUNPRIMARYSCHOOL">CCC KEI CHUN PRIMARY SCHOOL</option>
                <option value="CCCKEIFAATPRIMARYSCHOOL">CCC KEI FAAT PRIMARY SCHOOL</option>
                <option value="CCCKEITOSECONDARYSCHOOL">CCC KEI TO SECONDARY SCHOOL</option>
                <option value="CCCKEITSZPRIMARYSCHOOL">CCC KEI TSZ PRIMARY SCHOOL</option>
                <option value="CELKIMEDICALCOMPANY">CELKI MEDICAL COMPANY</option>
                <option value="CHAIWANKOKCATHOLICPRISCH">CHAI WAN KOK CATHOLIC PRI SCH</option>
                <option value="CHIFUFAYUENLIMITED">CHI FU FA YUEN LIMITED</option>
                <option value="CHILINBUDDHISTPRISCH">CHI LIN BUDDHIST PRI SCH</option>
                <option value="CHINAGRADUATESCHOFTHEOLOGY">CHINA GRADUATE SCH OF THEOLOGY</option>
                <option value="CHINAHOLINESSCHURCHLSCOLL">CHINA HOLINESS CHURCH L S COLL</option>
                <option value="CHINAINTLTRASER(HK)HLTD">CHINA INTL TRA SER (HK) H LTD</option>
                <option value="CHINALIFEINS(OVERSEA)COL">CHINA LIFE INS (OVERSEA) CO L</option>
                <option value="CHINAMOBILEHKCLTD-SVSIMC">CHINA MOBILE HK C LTD-SV SIM C</option>
                <option value="CHINAMOBILEHONGKONGCOLTD">CHINA MOBILE HONG KONG CO LTD</option>
                <option value="CHINAMOTIONTELECOM">CHINA MOTION TELECOM</option>
                <option value="CHINAOVERSEASPROPERTYSERVL">CHINA OVERSEAS PROPERTY SERV L</option>
                <option value="CHINATRAVELSERVICE(HK)LTD">CHINA TRAVEL SERVICE (HK) LTD</option>
                <option value="CHINAUNICOM(HK)OPERATIONSL">CHINA UNICOM (HK) OPERATIONS L</option>
                <option value="CHINA-HONGKONGTELECOMLIMITED">CHINA-HONGKONG TELECOM LIMITED</option>
                <option value="CHINAOIL(HK)CORPORATIONLTD">CHINAOIL (HK) CORPORATION LTD</option>
                <option value="CHINESEESTATES,GROUP">CHINESE ESTATES, GROUP</option>
                <option value="CHINESEMEDICINECOUNCILOFHK">CHINESE MEDICINE COUNCIL OF HK</option>
                <option value="CHINESEMETHODISTS,TANNERHIL">CHINESE METHODIST S,TANNER HIL</option>
                <option value="CHINESERHENISHCHURCH,THE">CHINESE RHENISH CHURCH, THE</option>
                <option value="CHINESEYMCACOLLEGE">CHINESE YMCA COLLEGE</option>
                <option value="CHINESEYMCAPRIMARYSCHOOL">CHINESE YMCA PRIMARY SCHOOL</option>
                <option value="CHOIFUNGHONGCOMPANYLIMITED">CHOI FUNG HONG COMPANY LIMITED</option>
                <option value="CHOIWANST.JOSEPH'SPRISCH">CHOI WAN ST. JOSEPH'S PRI SCH</option>
                <option value="CHOWSANGSANGJEWELLERY">CHOW SANG SANG JEWELLERY</option>
                <option value="CHR&amp;amp;MISALLISKPRISCH">CHR &amp; MIS ALLI S K PRI SCH</option>
                <option value="CHRISTASWCMCOLLEGE">CHRIST A SWCM COLLEGE</option>
                <option value="CHRISTCOLLEGE">CHRIST COLLEGE</option>
                <option value="CHRISTIANASCCMCOLLEGE">CHRISTIAN A S C C M COLLEGE</option>
                <option value="CHRISTIANACTION">CHRISTIAN ACTION</option>
                <option value="CHRISTIANALLICHCPSCH">CHRISTIAN ALLI CHC P SCH</option>
                <option value="CHRISTIANFAMILYSVCCENTRE">CHRISTIAN FAMILY SVC CENTRE</option>
                <option value="CHUHAICOLLEGEOFHIGHEREDU">CHU HAI COLLEGE OF HIGHER EDU</option>
                <option value="CHUNLEIPRIMARYSCHOOL">CHUN LEI PRIMARY SCHOOL</option>
                <option value="CIGNAWORLDWIDELIFEICOLTD">CIGNA WORLDWIDE LIFE I CO LTD</option>
                <option value="CITYPUBLISHINGLTD">CITY PUBLISHING LTD</option>
                <option value="CITYUNIVERSITYOFHONGKONG">CITY UNIVERSITY OF HONG KONG</option>
                <option value="CITYBASEPROPERTYMANAGLTD">CITYBASE PROPERTY MANAG LTD</option>
                <option value="CLOTHINGINDUSTRYTRAININGAUT">CLOTHING INDUSTRY TRAINING AUT</option>
                <option value="CLPPOWER">CLP POWER</option>
                <option value="COMMUNITYCHEST(E-DONATION)">COMMUNITY CHEST (E-DONATION)</option>
                <option value="COMNETTELECOM(HK)LIMITED">COMNET TELECOM (HK) LIMITED</option>
                <option value="COMPANIESREGISTRY">COMPANIES REGISTRY</option>
                <option value="COMPASSGROUPHONGKONGLTD">COMPASS GROUP HONG KONG LTD</option>
                <option value="CONCORDIALUTHERANSCHOOL">CONCORDIA LUTHERAN SCHOOL</option>
                <option value="CONSUMERCOUNCIL">CONSUMER COUNCIL</option>
                <option value="COUNTRYHOUSEPROPERTYMGTLTD">COUNTRY HOUSE PROPERTY MGT LTD</option>
                <option value="COURTPAYMENT">COURT PAYMENT</option>
                <option value="CPCYAODAOSECONDARYSCHOOL">CPC YAO DAO SECONDARY SCHOOL</option>
                <option value="CSL">CSL</option>
                <option value="CSL(PCCW-HKTMOBILESERVICE)">CSL (PCCW-HKT MOBILE SERVICE)</option>
                <option value="CUHKFAACHANCHUNHASECSCH">CUHK FAA CHAN CHUN HA SEC SCH</option>
                <option value="CUTWCOMMUNITYCOLLEGE">CUTW COMMUNITY COLLEGE</option>
                <option value="DAHSINGLIFE">DAH SING LIFE</option>
                <option value="DANNYCATERINGSERVICELTD">DANNY CATERING SERVICE LTD</option>
                <option value="DELIFRESHLIMITED">DELI FRESH LIMITED</option>
                <option value="DELIHONOURGOURMET">DELI HONOUR GOURMET</option>
                <option value="DELICIOUSCHEFKCATERINGLTD">DELICIOUS CHEF K CATERING LTD</option>
                <option value="DIAMONDHOMESPRINGWATER">DIAMOND HOME SPRING WATER</option>
                <option value="DIOCESANGIRLS'SCHOOL">DIOCESAN GIRLS' SCHOOL</option>
                <option value="DISCOVERYBAYSERVMANAGELTD">DISCOVERY BAY SERV MANAGE LTD</option>
                <option value="DISCOVERYCOLLEGE-MISCFEE">DISCOVERY COLLEGE - MISC FEE</option>
                <option value="DISCOVERYPARKCOMMSERVICESL">DISCOVERY PARK COMM SERVICES L</option>
                <option value="DOUBLECOVEMANAGEMENTLIMITED">DOUBLE COVE MANAGEMENT LIMITED</option>
                <option value="DRAINAGEAUTHORITY">DRAINAGE AUTHORITY</option>
                <option value="ECPAYMENT">E C PAYMENT</option>
                <option value="ETBUSINESSCOLLEGE">E T BUSINESS COLLEGE</option>
                <option value="EASYGOLD">EASY GOLD</option>
                <option value="ECOX.COM.HK">ECOX.COM.HK</option>
                <option value="EDMALL(HONGKONG)LTD">EDMALL (HONG KONG) LTD</option>
                <option value="EGLTOURSCOMPANYLIMITED">EGL TOURS COMPANY LIMITED</option>
                <option value="ELCSS-HK">ELCSS-HK</option>
                <option value="EMF">EMF</option>
                <option value="ENGLISHTOWN">ENGLISHTOWN</option>
                <option value="ENVIRONMENTALPROTECTIONDEPT">ENVIRONMENTAL PROTECTION DEPT</option>
                <option value="ESTATE-CAREPROPERTYMGTLTD">ESTATE-CARE PROPERTY MGT LTD</option>
                <option value="ESTORILCOURTM-ESTORILCOURT">ESTORIL COURT M-ESTORIL COURT</option>
                <option value="ETERNALEASTTOURSCOLTD">ETERNAL EAST TOURS CO LTD</option>
                <option value="FAIRWOODFASTFOODLIMITED">FAIRWOOD FAST FOOD LIMITED</option>
                <option value="FAMILYPLANNINGASSOOFHK">FAMILY PLANNING ASSO OF HK</option>
                <option value="FATTATHONG">FAT TAT HONG</option>
                <option value="FDBWACHOWCHINYAUSCHOOL">FDBWA CHOW CHIN YAU SCHOOL</option>
                <option value="FDBWASZETOHOSECSCHOOL">FDBWA SZETO HO SEC SCHOOL</option>
                <option value="FEDERATIONFORSELF-FINANCING">FEDERATION FOR SELF-FINANCING</option>
                <option value="FEDERATIONOFTHEHKPOLYUA">FEDERATION OF THE HK POLY U A</option>
                <option value="FEVAWORKSITEDUCATIONCENTRE">FEVA WORKS IT EDUCATION CENTRE</option>
                <option value="FITFORLIFEL&amp;amp;CSERVICES">FIT FOR LIFE L&amp;C SERVICES</option>
                <option value="FIXEDPENALTY(SMOKINGOFFENCES)">FIXED PENALTY(SMOKINGOFFENCES)</option>
                <option value="FKYCTUCKSHOP">FKYC TUCK SHOP</option>
                <option value="FLORAPLAZAMANAGEMENTLIMITED">FLORA PLAZA MANAGEMENT LIMITED</option>
                <option value="FOOD&amp;amp;ENVIRONMENTHYGIENE">FOOD &amp; ENVIRONMENT HYGIENE</option>
                <option value="FOREVERPETS">FOREVER PETS</option>
                <option value="FOUNTAINFOOD">FOUNTAIN FOOD</option>
                <option value="FOURSEASTRAVEL">FOUR SEAS TRAVEL</option>
                <option value="FREEMETHODISTMEILAMPRISCH">FREE METHODIST MEI LAM PRI SCH</option>
                <option value="FRUITFULFUELLIMITED">FRUITFUL FUEL LIMITED</option>
                <option value="FUHONGSOCIETY">FU HONG SOCIETY</option>
                <option value="FUKIENSECONDARYSCHOOL">FUKIEN SECONDARY SCHOOL</option>
                <option value="FUNGKAINO.1SECONDARYSCHOOL">FUNG KAI NO.1 SECONDARY SCHOOL</option>
                <option value="FWDLIFEINSURANCE">FWD LIFE INSURANCE</option>
                <option value="GERTRUDESIMONLUTHERANCOLLEG">GERTRUDE SIMON LUTHERAN COLLEG</option>
                <option value="GIVEME5">GIVE ME 5</option>
                <option value="GLAXOSMITHKLINELIMITED">GLAXOSMITHKLINE LIMITED</option>
                <option value="GLOBALCALLLIMITED">GLOBAL CALL LIMITED</option>
                <option value="GOLDENPROMISETRAVELAGENCYC">GOLDEN PROMISE TRAVEL AGENCY C</option>
                <option value="GOLDJOYHOLIDAYS">GOLDJOY HOLIDAYS</option>
                <option value="GOLDSTATESTRAVEL">GOLDSTATES TRAVEL</option>
                <option value="GOODYIELDPROPERTYMGTLTD">GOOD YIELD PROPERTY MGT LTD</option>
                <option value="GOODWELLPROPMANAGEMENTLTD">GOODWELL PROP MANAGEMENT LTD</option>
                <option value="GOVTGENERALDEMANDNOTE">GOVT GENERAL DEMAND NOTE</option>
                <option value="GOVTSTUDENTLOANREPAYMENT">GOVT STUDENT LOAN REPAYMENT</option>
                <option value="GRANDEURPROPERTYMGTCOLTD">GRANDEUR PROPERTY MGT CO LTD</option>
                <option value="GUARDIANPROPERTYMGTLTD">GUARDIAN PROPERTY MGT LTD</option>
                <option value="HEAL-EDWICKINDCTR">H E A L-EDWICK IND CTR</option>
                <option value="HEALTD-FORTISTOWER">H E A LTD - FORTIS TOWER</option>
                <option value="HEALTD-KING'SCOURT">H E A LTD - KING'S COURT</option>
                <option value="HKARTSCENTRE-HKARTSCH">H K ARTS CENTRE - H K ART SCH</option>
                <option value="HANGLUNGREAGLTD-RENTAL">HANG LUNG R E AG LTD - RENTAL</option>
                <option value="HANGONESTATEMANAGEMENTLTD">HANG ON ESTATE MANAGEMENT LTD</option>
                <option value="HANGSENGINSURANCE(LIFE)">HANG SENG INSURANCE (LIFE)</option>
                <option value="HANGSENGMANAGEMENTCOLLEGE">HANG SENG MANAGEMENT COLLEGE</option>
                <option value="HANGYICKPROPERTIESMGTLTD">HANG YICK PROPERTIES MGT LTD</option>
                <option value="HARBOURFRONTLANDMARKPSLTD">HARBOURFRONT LANDMARK P S LTD</option>
                <option value="HARMONYHOUSELTD">HARMONY HOUSE LTD</option>
                <option value="HARRIMANMGTSERVLTD-BELLAGIO">HARRIMAN MGT SERV LTD-BELLAGIO</option>
                <option value="HAVENOFHOPEWOOPINGCARE&amp;amp;">HAVEN OF HOPE WOO PING CARE &amp;</option>
                <option value="HEALTHSMARTLTD">HEALTH SMART LTD</option>
                <option value="HEEPHONGSOCIETY">HEEP HONG SOCIETY</option>
                <option value="HEIFERINTERNATIONALHKLTD">HEIFER INTERNATIONAL HK LTD</option>
                <option value="HELIXSYSTEMLIMITED">HELIX SYSTEM LIMITED</option>
                <option value="HENRIETTASECONDARYSCHOOL">HENRIETTA SECONDARY SCHOOL</option>
                <option value="HHCKLABUDDHISTMKCMESECSCH">HHCKLA BUDDHIST MKCM E SEC SCH</option>
                <option value="HHCKLABUDDHISTWISDOMPRIS">HHCKLA BUDDHIST WISDOM PRI S</option>
                <option value="HIPSHINGHONG">HIP SHING HONG</option>
                <option value="HKANTI-CANCERSOCIETY">HK ANTI-CANCER SOCIETY</option>
                <option value="HKAUTOMOBILEASSOCIATION">HK AUTOMOBILE ASSOCIATION</option>
                <option value="HKBAPTISTCONVENTIONPRISCHO">HK BAPTIST CONVENTION PRI SCHO</option>
                <option value="HKBAPTISTU(E-DONATION)">HK BAPTIST U (E-DONATION)</option>
                <option value="HKBAPTISTUNIVERSITY">HK BAPTIST UNIVERSITY</option>
                <option value="HKBUDDHISTSOCFTBLINDLTD">HK BUDDHIST SOC F T BLIND LTD</option>
                <option value="HKCOLLEGEOFTECHNOLOGY">HK COLLEGE OF TECHNOLOGY</option>
                <option value="HKCOMMITTEEOFUNICEF">HK COMMITTEE OF UNICEF</option>
                <option value="HKDOWNSYNDROMEASSO.THE">HK DOWN SYNDROME ASSO. THE</option>
                <option value="HKEXPORTCREDITINSURCORP">HK EXPORT CREDIT INSUR CORP</option>
                <option value="HKFAMILYWELFARESOCIETY">HK FAMILY WELFARE SOCIETY</option>
                <option value="HKFEDERATIONOFYOUTHGPS">HK FEDERATION OF YOUTH GPS</option>
                <option value="HKFINCONSULTANTSHLDSLTD">HK FIN CONSULTANTS HLDS LTD</option>
                <option value="HKINSTOFHUMANRESMANAGLTD">HK INST OF HUMAN RES MANAG LTD</option>
                <option value="HKINSTITUTEOFED(E-DONATION)">HK INSTITUTE OF ED(E-DONATION)</option>
                <option value="HKINSTITUTEOFTECHNOLOGY">HK INSTITUTE OF TECHNOLOGY</option>
                <option value="HKKWAISHINGLUTHERANPRISCH">HK KWAI SHING LUTHERAN PRI SCH</option>
                <option value="HKNEURO-MUSCULARDISASSLTD">HK NEURO-MUSCULAR DIS ASS LTD</option>
                <option value="HKPARALYMPICCOM&amp;amp;SPORTSASS">HK PARALYMPIC COM &amp; SPORTS ASS</option>
                <option value="HKPHABASSOCIATION">HK PHAB ASSOCIATION</option>
                <option value="HKPOLYTECHNICU(E-DONATION)">HK POLYTECHNIC U (E-DONATION)</option>
                <option value="HKREDCROSS">HK RED CROSS</option>
                <option value="HKREDCROSSCHINARELIEFFUND">HK RED CROSS CHINA RELIEF FUND</option>
                <option value="HKSAFETYSERVASSOCIATIONLTD">HK SAFETY SERV ASSOCIATION LTD</option>
                <option value="HKSOCIETYFORTHEAGED,THE">HK SOCIETY FOR THE AGED, THE</option>
                <option value="HKSOCIETYFORTHEBLIND,THE">HK SOCIETY FOR THE BLIND, THE</option>
                <option value="HKSTJOHNAMBULANCE">HK ST JOHN AMBULANCE</option>
                <option value="HKWOMENCHRISTIANCOUNCIL">HK WOMEN CHRISTIAN COUNCIL</option>
                <option value="HKYWCA">HK YWCA</option>
                <option value="HKBN">HKBN</option>
                <option value="HKBN-IDD1666">HKBN-IDD1666</option>
                <option value="HKBUASWONGKAMFAI&amp;amp;PSCH">HKBUAS WONG KAM FAI &amp; P SCH</option>
                <option value="HKMCOFSEVENTH-DAYADVENTISTS">HKMC OF SEVENTH-DAY ADVENTISTS</option>
                <option value="HKPPEA">HKPPEA</option>
                <option value="HKPTU">HKPTU</option>
                <option value="HKTA">HKTA</option>
                <option value="HKTATANGHINMEM.SS">HKTA TANG HIN MEM. S S</option>
                <option value="HKTATHEYUENYUENINO.1SECS">HKTA THE YUENYUEN I NO.1 SEC S</option>
                <option value="HKUSCHOOLOFPROF&amp;amp;CONEDU">HKU SCHOOL OF PROF &amp; CON EDU</option>
                <option value="HKUELIMITED">HKUE LIMITED</option>
                <option value="HKUST">HKUST</option>
                <option value="HKUST(E-DONATION)">HKUST (E-DONATION)</option>
                <option value="HKUST-DONATION/OTHERS">HKUST-DONATION/OTHERS</option>
                <option value="HOYUCOLLEGE&amp;amp;PRIMARYSCHOOL">HO YU COLLEGE &amp; PRIMARY SCHOOL</option>
                <option value="HOIPASTGOV'TPRIMARYSCHOOL">HOI PA ST GOV'T PRIMARY SCHOOL</option>
                <option value="HOIPINGCHAMBEROFCOMMSECS">HOI PING CHAMBER OF COMM SEC S</option>
                <option value="HOITAITOURSLTD">HOI TAI TOURS LTD</option>
                <option value="HOLIDAYEXPRESSTRAVELSERLTD">HOLIDAY EXPRESS TRAVEL SER LTD</option>
                <option value="HOLYANGELSCSCHOOL">HOLY ANGELS C SCHOOL</option>
                <option value="HOLYCARPENTERPRIMARYSCHOOL">HOLY CARPENTER PRIMARY SCHOOL</option>
                <option value="HOLYFAMILYCANOSSIANSCHOOL">HOLY FAMILY CANOSSIAN SCHOOL</option>
                <option value="HOLYFAMILYCANOSSIAN(KWT)">HOLY FAMILY CANOSSIAN(KWT)</option>
                <option value="HOMESMARTSERVICESLIMITED">HOMESMART SERVICES LIMITED</option>
                <option value="HONHINGENTERPRISESLIMITED">HON HING ENTERPRISES LIMITED</option>
                <option value="HONGCHIASSOCIATION">HONG CHI ASSOCIATION</option>
                <option value="HONGKONG&amp;amp;CHINAGAS(TOWNGAS)">HONG KONG &amp; CHINA GAS(TOWNGAS)</option>
                <option value="HONGKONGAGEDCONCERNLIMITED">HONG KONG AGED CONCERN LIMITED</option>
                <option value="HONGKONGARCHERYASSOCIATION">HONG KONG ARCHERY ASSOCIATION</option>
                <option value="HONGKONGBLINDUNION">HONG KONG BLIND UNION</option>
                <option value="HONGKONGCOMMUNITYCHEST">HONG KONG COMMUNITY CHEST</option>
                <option value="HONGKONGDESIGNCENTRE">HONG KONG DESIGN CENTRE</option>
                <option value="HONGKONGEDUCATIONCITYLTD">HONG KONG EDUCATION CITY LTD</option>
                <option value="HONGKONGHOUSINGAUTHORITY">HONG KONG HOUSING AUTHORITY</option>
                <option value="HONGKONGHOUSINGSOCIETY">HONG KONG HOUSING SOCIETY</option>
                <option value="HONGKONGINTERNATIONALSCHOOL">HONG KONG INTERNATIONAL SCHOOL</option>
                <option value="HONGKONGPRINTINGCENTRE">HONG KONG PRINTING CENTRE</option>
                <option value="HONGKONGPROPERTY">HONG KONG PROPERTY</option>
                <option value="HONGKONGRESORTCO.LTD">HONG KONG RESORT CO. LTD</option>
                <option value="HONGKONGSEASCHOOL">HONG KONG SEA SCHOOL</option>
                <option value="HONGKONGSTORAGE">HONG KONG STORAGE</option>
                <option value="HONGKONGTRUELIGHTCOLLEGE">HONG KONG TRUE LIGHT COLLEGE</option>
                <option value="HONGKONGWATERBOTTLING">HONG KONG WATER BOTTLING</option>
                <option value="HONGLOKYUENPROPERTYMGTCOL">HONG LOKYUEN PROPERTY MGT CO L</option>
                <option value="HONGTHAITRAVELSERVICESLTD">HONG THAI TRAVEL SERVICES LTD</option>
                <option value="HONGYIPSERVICECOMPANYLTD">HONG YIP SERVICE COMPANY LTD</option>
                <option value="HONGKONGELECTRIC">HONGKONG ELECTRIC</option>
                <option value="HOPYATCHURCHSCHOOL">HOP YAT CHURCH SCHOOL</option>
                <option value="HOPEWELLPROPERTYMGTCOLTD">HOPEWELL PROPERTY MGT CO LTD</option>
                <option value="HOSPITALAUTHORITY">HOSPITAL AUTHORITY</option>
                <option value="HPCC">HPCC</option>
                <option value="HSBCLIFE(INT'L)LTD">HSBC LIFE (INT'L) LTD</option>
                <option value="HUTCHISONESTAGTLTDBLBKBG">HUTCHISON EST AGT LTD BL BK BG</option>
                <option value="HUTCHISONESTATEAGENTSLTD">HUTCHISON ESTATE AGENTS LTD</option>
                <option value="HUTCHISONGLOBALCOMM.(HGC)">HUTCHISON GLOBAL COMM. (HGC)</option>
                <option value="HUTCHISONTELECOM">HUTCHISON TELECOM</option>
                <option value="HYFCOTRAVELAGENCYLIMITED">HYFCO TRAVEL AGENCY LIMITED</option>
                <option value="I-CABLETELECOMLIMITED">I-CABLE TELECOM LIMITED</option>
                <option value="IDD1507">IDD 1507</option>
                <option value="IDD1538INTERNATIONALTELELTD">IDD1538 INTERNATIONAL TELE LTD</option>
                <option value="IMCOFPLKFONGWONGKAMCHUEN">IMC OF PLK FONG WONG KAM CHUEN</option>
                <option value="IMMACULATEHEARTOFMARYCOLLE">IMMACULATE HEART OF MARY COLLE</option>
                <option value="INLANDREVENUEDEPARTMENT">INLAND REVENUE DEPARTMENT</option>
                <option value="INT'LPROPERTYMANAGLTD">INT'L PROPERTY MANAG LTD</option>
                <option value="INT'LSOCIALSERVICEHKBRANCH">INT'L SOCIAL SERVICE HK BRANCH</option>
                <option value="INTERACTIVEINFOHIGHWAYLTD">INTERACTIVE INFO HIGHWAY LTD</option>
                <option value="INTERNATIONALCHRISTIANSCHOOL">INTERNATIONAL CHRISTIAN SCHOOL</option>
                <option value="IPRINT.HK">IPRINT.HK</option>
                <option value="ISLANDSOUTHPROPMANAGELTD">ISLAND SOUTH PROP MANAGE LTD</option>
                <option value="ISSEASTPOINTPROPERTIESLTD">ISS EASTPOINT PROPERTIES LTD</option>
                <option value="ISSEASTPOINTPROPERTYMGTLTD">ISS EASTPOINT PROPERTY MGT LTD</option>
                <option value="IUSHANSCHOOL">IU SHAN SCHOOL</option>
                <option value="JACKELPORTERCOMPANYLIMITED">JACKEL PORTER COMPANY LIMITED</option>
                <option value="JALSATELLITETRAVELCOLTD">JAL SATELLITE TRAVEL CO LTD</option>
                <option value="JETOUR">JETOUR</option>
                <option value="JETOURHOLIDAYLTD">JETOUR HOLIDAY LTD</option>
                <option value="JETSOMOBILESERVICE">JETSO MOBILE SERVICE</option>
                <option value="JOBSDBHKLTD">JOBS DB HK LTD</option>
                <option value="JONESLL&amp;amp;RESMGTSERLTD">JONES L L &amp; RES MGT SER LTD</option>
                <option value="JORDANVALLEYSTJOSEPH'SCP">JORDAN VALLEY ST JOSEPH'S C P</option>
                <option value="JUBILEEINTLTOURCENTRELTD">JUBILEE INTL TOUR CENTRE LTD</option>
                <option value="JUMPSTARTBUSINESSCENTRE">JUMPSTART BUSINESS CENTRE</option>
                <option value="JUPAS">JUPAS</option>
                <option value="KALINGSCHOFTHEPRECIOUSB">KA LING SCH OF THE PRECIOUS B</option>
                <option value="KAISHINGMGTSERVICESLTD">KAI SHING MGT SERVICES LTD</option>
                <option value="KAIWINGINSURANCEAGENCY">KAI WING INSURANCE AGENCY</option>
                <option value="KEISANSECONDARYSCHOOL">KEI SAN SECONDARY SCHOOL</option>
                <option value="KENNEDYSCHOOL-MISCFEE">KENNEDY SCHOOL - MISC FEE</option>
                <option value="KERRYPROPERTYMGTSERVICESLT">KERRY PROPERTY MGT SERVICES LT</option>
                <option value="KINGGEORGEVSCHOOL">KING GEORGE V SCHOOL</option>
                <option value="KINGYIPTRAVELCOLTD">KING YIP TRAVEL CO LTD</option>
                <option value="KING'SCOLLEGEOBASSOPSCH">KING'S COLLEGE O B ASSO P SCH</option>
                <option value="KITSAMLAMBINGYIMSECSCH">KIT SAM LAM BING YIM SEC SCH</option>
                <option value="KLBAYST.JOHNTHEBCPRISCH">KLBAY ST.JOHN THE B C PRI SCH</option>
                <option value="KLNTONGBISHOPWALSHCSCHOOL">KLN TONG BISHOP WALSH C SCHOOL</option>
                <option value="KLNCITYBAPTISTCHAYNIENPS">KLNCITY BAPTIST C HAY NIEN P S</option>
                <option value="KOWLOONTRUELIGHTMIDDLESCH">KOWLOON TRUE LIGHT MIDDLE SCH</option>
                <option value="KWAICHUNGMETHODISTCOLLEGE">KWAI CHUNG METHODIST COLLEGE</option>
                <option value="KWOONCHUNGMOTORSCO.LTD.">KWOON CHUNG MOTORS CO. LTD.</option>
                <option value="LSTYOUNGKOHSIAOLINSSCH">L S T YOUNG KO HSIAO LIN S SCH</option>
                <option value="LAICHIKOKCATHOLICPRIMARYS">LAICHIKOK CATHOLIC PRIMARY S</option>
                <option value="LAMTSUENPUBLICWONGFOOKLUE">LAM TSUEN PUBLIC WONG FOOK LUE</option>
                <option value="LANDSDEPT-GOVERNMENTRENT">LANDS DEPT - GOVERNMENT RENT</option>
                <option value="LBS">LBS</option>
                <option value="LEECHITATMEMORIALSCHOOL">LEE CHI TAT MEMORIAL SCHOOL</option>
                <option value="LEGALAIDDEPARTMENT">LEGAL AID DEPARTMENT</option>
                <option value="LEIMUKSHUECATHOLICPRISCH">LEI MUK SHUE CATHOLIC PRI SCH</option>
                <option value="LEUNGSHEKCHEECOLLEGE">LEUNG SHEK CHEE COLLEGE</option>
                <option value="LIGHTANDLOVEHOMELIMITED">LIGHT AND LOVE HOME LIMITED</option>
                <option value="LINGTOCATHOLICPRISCHOOL">LING TO CATHOLIC PRI SCHOOL</option>
                <option value="LINGNANUNIVERSITY">LINGNAN UNIVERSITY</option>
                <option value="LLCEWUNSECONDARYSCHOOL">LLC E WUN SECONDARY SCHOOL</option>
                <option value="LOKSINTONGBENEVOSOC,KLN">LOK SIN TONG BENEVO SOC, KLN</option>
                <option value="LOKWAHCATHOLICPRISCHOOL">LOK WAH CATHOLIC PRI SCHOOL</option>
                <option value="LOTUSTOURSLIMITED">LOTUS TOURS LIMITED</option>
                <option value="LSGCATERINGCHINALTD">LSG CATERING CHINA LTD</option>
                <option value="LUICHEUNGKWONGLUTHERANCOLL">LUI CHEUNG KWONG LUTHERAN COLL</option>
                <option value="LUIMINGCHOILUTHERANCOLLEGE">LUI MING CHOI LUTHERAN COLLEGE</option>
                <option value="LUNGKONGWFSLLWFSECSCH">LUNG KONG WFSL L W F SEC SCH</option>
                <option value="MAONSHANLINGLIANGPRISCH">MA ON SHAN LING LIANG PRI SCH</option>
                <option value="MACY'SFOODSERVICES">MACY'S FOOD SERVICES</option>
                <option value="MAGICSMART">MAGIC SMART</option>
                <option value="MAINSHINEDEVLTD-GOODVIEW">MAIN SHINE DEV LTD-GOODVIEW</option>
                <option value="MAINSHINEDEVELOPMENTLTD">MAIN SHINE DEVELOPMENT LTD</option>
                <option value="MAISONPLATINUMSERVICECOLTD">MAISON PLATINUM SERVICE CO LTD</option>
                <option value="MANGROVE(TUCKSHOPMGT)LTD">MANGROVE (TUCK SHOP MGT) LTD</option>
                <option value="MANULIFE">MANULIFE</option>
                <option value="MANULIFEPFTRUST(MPF)">MANULIFE P F TRUST (MPF)</option>
                <option value="MANYWELLS">MANY WELLS</option>
                <option value="MARYOFPROVIDENCEPRIMARYSCH">MARY OF PROVIDENCE PRIMARY SCH</option>
                <option value="MASSMUTUALASIA">MASSMUTUAL ASIA</option>
                <option value="MAXIM'SCATERERSLIMITED">MAXIM'S CATERERS LIMITED</option>
                <option value="MAXIMTELIDD1548">MAXIMTEL IDD1548</option>
                <option value="MEDECINSSANSFRONTIERES">MEDECINS SANS FRONTIERES</option>
                <option value="MEGLIMITED">MEG LIMITED</option>
                <option value="MENTALHEALTHASSOOFHK,THE">MENTAL HEALTH ASSO OF HK, THE</option>
                <option value="METHODISTCENTRE">METHODIST CENTRE</option>
                <option value="METROCITYMANAGEMENTLIMITED">METRO CITY MANAGEMENT LIMITED</option>
                <option value="METROHARBOURVIEWMGTLIMITED">METRO HARBOURVIEW MGT LIMITED</option>
                <option value="MIDLANDREALTY">MIDLAND REALTY</option>
                <option value="MIRAMARTRAVEL">MIRAMAR TRAVEL</option>
                <option value="MODERNPLAZAMANAGEMENTLTD">MODERN PLAZA MANAGEMENT LTD</option>
                <option value="MORETELECOM">MORE TELECOM</option>
                <option value="MORNINGSTARTRAVELSERVLTD">MORNING STAR TRAVEL SERV LTD</option>
                <option value="MOTORVEH.IDLING-FIXEDPENALTY">MOTOR VEH. IDLING-FIXEDPENALTY</option>
                <option value="MRSCHENGYAMONSCHOOL">MRS CHENG YAM ON SCHOOL</option>
                <option value="MTRCORP-PROPERTYMGT">MTR CORP-PROPERTY MGT</option>
                <option value="MURRAYCATERINGCOLTD">MURRAY CATERING CO LTD</option>
                <option value="MURRAYFOOD&amp;amp;BEVERAGE">MURRAY FOOD &amp; BEVERAGE</option>
                <option value="NEIGHBRHODADVICE-ACTION">NEIGHBRHOD ADVICE-ACTION</option>
                <option value="NEWCHARMMANAGEMENTLIMITED">NEW CHARM MANAGEMENT LIMITED</option>
                <option value="NEWLIFEPSYREHABASSO">NEW LIFE PSY REHAB ASSO</option>
                <option value="NEWWORLDTELECOM">NEW WORLD TELECOM</option>
                <option value="NEWMANCATHOLICCOLLEGE">NEWMAN CATHOLIC COLLEGE</option>
                <option value="NGCLAN'SASSOTAIPAKMEMSCH">NG CLAN'S ASSO TAI PAK MEM SCH</option>
                <option value="NINETOFIVECATERINGSERVICES">NINE TO FIVE CATERING SERVICES</option>
                <option value="NTKLEARNINGCENTRE">NTK LEARNING CENTRE</option>
                <option value="NWMOBILITY-PREPAIDSIM">NW MOBILITY-PREPAID SIM</option>
                <option value="OCEANPARKCORP">OCEAN PARK CORP</option>
                <option value="OFFICEOFTHECOMMAUTHORITY">OFFICE OF THE COMM AUTHORITY</option>
                <option value="ONKEEDRYSEAFOODCO.LTD.">ON KEE DRY SEAFOOD CO. LTD.</option>
                <option value="ONE.TELLTD1686">ONE.TEL LTD 1686</option>
                <option value="ONEASIANETWORKLIMITED">ONEASIA NETWORK LIMITED</option>
                <option value="ONLINEBENGSENGCOLTD">ONLINE BENG SENG CO LTD</option>
                <option value="OPENUNIVERSITY(E-DONATION)">OPEN UNIVERSITY (E-DONATION)</option>
                <option value="OTICFOUNDATION">OTIC FOUNDATION</option>
                <option value="OXFAMHONGKONG">OXFAM HONG KONG</option>
                <option value="PACKAGETOURS(HK)LIMITED">PACKAGE TOURS (HK) LIMITED</option>
                <option value="PACNETINTERNET(HK)LIMITED">PACNET INTERNET (HK) LIMITED</option>
                <option value="PAKKAUCOLLEGE">PAK KAU COLLEGE</option>
                <option value="PAKSHINGTONG">PAK SHING TONG</option>
                <option value="PAOCKACHISECONDARYSCHOOL">PAOC KA CHI SECONDARY SCHOOL</option>
                <option value="PARAMATTAESTATEMANAGLTD">PARAMATTA ESTATE MANAG LTD</option>
                <option value="PARSONSMUSICLIMITED">PARSONS MUSIC LIMITED</option>
                <option value="PASONAEDUCATION">PASONA EDUCATION</option>
                <option value="PCCW">PCCW</option>
                <option value="PCCW(NETVIGATOR/NOWTVBILLS)">PCCW (NETVIGATOR/NOW TV BILLS)</option>
                <option value="PENTECOSTALGINMAOSHENGPS">PENTECOSTAL GIN MAO SHENG P S</option>
                <option value="PENTECOSTALYULEUNGFATPRIS">PENTECOSTAL YU LEUNG FAT PRI S</option>
                <option value="PERFECTWORLDCOMPANYLIMITED">PERFECT WORLD COMPANY LIMITED</option>
                <option value="PETDOGHK.COM">PETDOGHK.COM</option>
                <option value="PIGGYWHITEPROFLAUNDRY">PIGGYWHITE PROF LAUNDRY</option>
                <option value="PIOOFRATING&amp;amp;VALUATIONDEPT">PIO OF RATING &amp; VALUATION DEPT</option>
                <option value="PLAYSKI&amp;amp;SNOWBOARD">PLAY SKI &amp; SNOWBOARD</option>
                <option value="PLKHKTAOISTAYUENYUENPS">PLK HK TAOIST A YUEN YUEN P S</option>
                <option value="PLKLOKITSING(1983)COLLEGE">PLK LO KIT SING (1983) COLLEGE</option>
                <option value="POKOKPRIMARYSCHOOL">PO KOK PRIMARY SCHOOL</option>
                <option value="POLEUNGKUK">PO LEUNG KUK</option>
                <option value="POLEUNGKUK(E-DONATION)">PO LEUNG KUK (E-DONATION)</option>
                <option value="POLEUNGKUKRIVERAINPRISCH">PO LEUNG KUK RIVERAIN PRI SCH</option>
                <option value="POHCHANKAIMEMORIALCOLLEGE">POH CHAN KAI MEMORIAL COLLEGE</option>
                <option value="POKOIHOSPITAL">POK OI HOSPITAL</option>
                <option value="POOITOMIDDLESCHOOL">POOI TO MIDDLE SCHOOL</option>
                <option value="POPEPAULVICOLLEGE">POPE PAUL VI COLLEGE</option>
                <option value="PRINT100.COM">PRINT100.COM</option>
                <option value="PROFESSIONALINSTITCATERINGL">PROFESSIONAL INSTIT CATERING L</option>
                <option value="PROJECTORBIS">PROJECT ORBIS</option>
                <option value="PROMISENETWORKPRINTINGLTD">PROMISE NETWORK PRINTING LTD</option>
                <option value="PROTECHPROPERTYMGTLTD">PROTECH PROPERTY MGT LTD</option>
                <option value="PRUDENTIALHONGKONGLIMITED">PRUDENTIAL HONG KONG LIMITED</option>
                <option value="PUIKIUMIDDLESCHOOL">PUI KIU MIDDLE SCHOOL</option>
                <option value="PUISHINGCATHOLICSECSCHOOL">PUI SHING CATHOLIC SEC SCHOOL</option>
                <option value="PUITAKCANOSSIANPSCHOOL">PUI TAK CANOSSIAN P SCHOOL</option>
                <option value="QUALIEDCOLLEGE">QUALIED COLLEGE</option>
                <option value="QUEEN'SCOLDBOYS'ASSOSECS">QUEEN'S C OLD BOYS' ASSO SEC S</option>
                <option value="RATES&amp;amp;GOVERNMENTRENT">RATES &amp; GOVERNMENT RENT</option>
                <option value="RE-ONHOLDINGSLIMITED">RE-ON HOLDINGS LIMITED</option>
                <option value="REALINKFINANCIALINFORMATION">REALINK FINANCIAL INFORMATION</option>
                <option value="RENAISSANCECOLLEGE-MISCFEE">RENAISSANCE COLLEGE-MISC FEE</option>
                <option value="RICHFIELDGROUP">RICHFIELD GROUP</option>
                <option value="ROOM+">ROOM+</option>
                <option value="ROYALELITESERVICECOLTD">ROYAL ELITE SERVICE CO LTD</option>
                <option value="RSCOMPONENTSLTD">RS COMPONENTS LTD</option>
                <option value="S.K.H.ST.JOSEPH'SPRISCHOOL">S.K.H. ST. JOSEPH'S PRI SCHOOL</option>
                <option value="SACREDHEARTCANOSSIANCOLLEGE">SACRED HEART CANOSSIAN COLLEGE</option>
                <option value="SACREDHEARTCANOSSIANSCHOOL">SACRED HEART CANOSSIAN SCHOOL</option>
                <option value="SAILINGBOATLUNCHEONSERVLTD">SAILING BOAT LUNCHEON SERV LTD</option>
                <option value="SALESIANYIPHONMILLPRSCH">SALESIAN YIP HON MILL PR SCH</option>
                <option value="SALESIANYIPHONPRSCH">SALESIAN YIP HON PR SCH</option>
                <option value="SALVATIONARMY,THE">SALVATION ARMY,THE</option>
                <option value="SAULUENPLBCOLTD">SAU LUEN PLB CO LTD</option>
                <option value="SAVILLSPROPMGTLTD">SAVILLS PROP MGT LTD</option>
                <option value="SCSTORAGE">SC STORAGE</option>
                <option value="SCANIA(HONGKONG)LIMITED">SCANIA (HONG KONG) LIMITED</option>
                <option value="SECURITIESANDFUTURESCOMM">SECURITIES AND FUTURES COMM</option>
                <option value="SHATINMETHODISTCOLLEGE">SHA TIN METHODIST COLLEGE</option>
                <option value="SHAKCHUNGSHANMCPSCHOOL">SHAK CHUNG SHAN M C P SCHOOL</option>
                <option value="SHAMTSENGCATHOLICPRIMARYS">SHAM TSENG CATHOLIC PRIMARY S</option>
                <option value="SHANTSUIPUBLICSCHOOL">SHAN TSUI PUBLIC SCHOOL</option>
                <option value="SHAOHUATRAVEL">SHAOHUA TRAVEL</option>
                <option value="SHARP-ROXY(HONGKONG)LTD">SHARP-ROXY (HONG KONG) LTD</option>
                <option value="SHATINMETHODISTPRISCHOOL">SHATIN METHODIST PRI SCHOOL</option>
                <option value="SHAUKIWANTSUNGTSINSCHOOL">SHAUKIWAN TSUNG TSIN SCHOOL</option>
                <option value="SHEKLEICATHOLICSECSCHOOL">SHEK LEI CATHOLIC SEC SCHOOL</option>
                <option value="SHEKLEIST.JOHN'SCATHOLICP">SHEK LEI ST. JOHN'S CATHOLIC P</option>
                <option value="SHELLGAS">SHELL GAS</option>
                <option value="SHENGKUNGHUIALLSAINTS'MS">SHENG KUNG HUI ALL SAINTS' M S</option>
                <option value="SHEUNGSHUICENTREMGTLIMITED">SHEUNG SHUI CENTRE MGT LIMITED</option>
                <option value="SHINETOWNTELLTD">SHINETOWN TEL LTD</option>
                <option value="SHUIONPROPERTIESMANAGELTD">SHUI ON PROPERTIES MANAGE LTD</option>
                <option value="SHUNLEECATHOLICSECSCHOOL">SHUN LEE CATHOLIC SEC SCHOOL</option>
                <option value="SHUNTAKFACHENGYUTUNGSEC">SHUN TAK F A CHENG YU TUNG SEC</option>
                <option value="SHUNTAKGROUPPROPMANAGDIV">SHUN TAK GROUP PROP MANAG DIV</option>
                <option value="SIGN.HK">SIGN.HK</option>
                <option value="SIKSIKYUEN">SIK SIK YUEN</option>
                <option value="SINCERITYTRAVEL">SINCERITY TRAVEL</option>
                <option value="SINOESTATESMGTLIMITED">SINO ESTATES MGT LIMITED</option>
                <option value="SINOPARKINGSERVICESLIMITED">SINO PARKING SERVICES LIMITED</option>
                <option value="SIXSIGMAINSTITUTELTD">SIX SIGMA INSTITUTE LTD</option>
                <option value="SKHBISHOPMOKSAUTSENGSECS">SKH BISHOP MOK SAU TSENG SEC S</option>
                <option value="SKHLADYMACLEHOSECTR">SKH LADY MACLEHOSE CTR</option>
                <option value="SKHLEUNGKWAIYEESECSCHOOL">SKH LEUNG KWAI YEE SEC SCHOOL</option>
                <option value="SKHTANGSHIUKINSECSCHOOL">SKH TANG SHIU KIN SEC SCHOOL</option>
                <option value="SKHYANLAAPPRIMARYSCHOOL">SKH YAN LAAP PRIMARY SCHOOL</option>
                <option value="SKHCWSTMICHAELPRISCH">SKHCW STMICHAEL PRISCH</option>
                <option value="SKYWARDSTRAVELLTD">SKYWARDS TRAVEL LTD</option>
                <option value="SMARTCHARMINGTRAVELLIMITED">SMART CHARMING TRAVEL LIMITED</option>
                <option value="SMARTHOME">SMART HOME</option>
                <option value="SMART-MENTORS(HK)LTD">SMART-MENTORS (HK) LTD</option>
                <option value="SMARTONE">SMARTONE</option>
                <option value="SOCIALWORKERSREGBOARD">SOCIAL WORKERS REG BOARD</option>
                <option value="SOCIETYFORAIDSCARELTD.THE">SOCIETY FOR AIDS CARE LTD. THE</option>
                <option value="SOCIETYOFJAPANESELANEDUHK">SOCIETY OF JAPANESE LAN EDU HK</option>
                <option value="SOUTHHORIZONSMANAGEMENTLTD">SOUTH HORIZONS MANAGEMENT LTD</option>
                <option value="SOWERSACTION">SOWERS ACTION</option>
                <option value="SPASTICSASSOOFHK">SPASTICS ASSO OF HK</option>
                <option value="SPHC(HOSPICECARE)">SPHC (HOSPICE CARE)</option>
                <option value="SRCITIZENHOMESAFETYASSO">SR CITIZEN HOME SAFETY ASSO</option>
                <option value="STCHARLESSCHOOL">ST CHARLES SCHOOL</option>
                <option value="STFRANCISOFASSISI'SCOLLEG">ST FRANCIS OF ASSISI'S COLLEG</option>
                <option value="STJAMES'SETTLEMENT">ST JAMES' SETTLEMENT</option>
                <option value="STPETER'SSECONDARYSCHOOL">ST PETER'S SECONDARY SCHOOL</option>
                <option value="STTERESASECONDARYSCHOOL">ST TERESA SECONDARY SCHOOL</option>
                <option value="ST.MARY'SCANOSSIANCOLLEGE">ST. MARY'S CANOSSIAN COLLEGE</option>
                <option value="ST.PAUL'SCOLLEGEPRIMARYSCH">ST. PAUL'S COLLEGE PRIMARY SCH</option>
                <option value="ST.PAUL'SHOSPITAL">ST. PAUL'S HOSPITAL</option>
                <option value="STANDARDLIFEASIA">STANDARD LIFE ASIA</option>
                <option value="STEWARDSLTD.">STEWARDS LTD.</option>
                <option value="STEWARDSPYKINDERGARTEN">STEWARDS P Y KINDERGARTEN</option>
                <option value="STEWARDSPOOIKEIPRIMARYSCH">STEWARDS POOI KEI PRIMARY SCH</option>
                <option value="STOREFRIENDLYSELFSTORAGEGR">STORE FRIENDLY SELF STORAGE GR</option>
                <option value="SUICIDEPREVENTIONSERVICESLD">SUICIDE PREVENTION SERVICES LD</option>
                <option value="SUNBUSLIMITED">SUN BUS LIMITED</option>
                <option value="SUNISLANDEDUCATIONFLTD">SUN ISLAND EDUCATION F LTD</option>
                <option value="SUNLIFEHONGKONGLIMITED">SUN LIFE HONG KONG LIMITED</option>
                <option value="SUNNETWORK(HONGKONG)LTD">SUN NETWORK (HONG KONG) LTD</option>
                <option value="SUNSMARTV-PLUS">SUN SMART V-PLUS</option>
                <option value="SUNFLOWERTRAVELSERVICELTD">SUNFLOWER TRAVEL SERVICE LTD</option>
                <option value="SUNPACTOURS&amp;amp;TRAVELLTD">SUNPAC TOURS &amp; TRAVEL LTD</option>
                <option value="SUNSHINECITYPROPERTYMGTLTD">SUNSHINE CITY PROPERTY MGT LTD</option>
                <option value="SUPREMEMGTSERVICESLTD">SUPREME MGT SERVICES LTD</option>
                <option value="SWIRETRAVELLIMITED">SWIRE TRAVEL LIMITED</option>
                <option value="SYNERGISMGTSERVICESLTD">SYNERGIS MGT SERVICES LTD</option>
                <option value="SYSTECHTELECOM">SYSTECH TELECOM</option>
                <option value="T.W.G.HS.YOWKAMYUENCOLLEGE">T.W.G.HS. YOW KAM YUEN COLLEGE</option>
                <option value="TAIPOBAPTISTPUBLICSCHOOL">TAI PO BAPTIST PUBLIC SCHOOL</option>
                <option value="TAIPOKAUYANCOLLEGE">TAI PO KAU YAN COLLEGE</option>
                <option value="TAIPOOMPSPLOVERCOVEPTA">TAI PO O M P S PLOVER COVE PTA</option>
                <option value="TAIPOOLDMARKETPUBSCHPTA">TAI PO OLD MARKET PUB SCH PTA</option>
                <option value="TAIPOSAMYUKSECSCHOOL">TAI PO SAM YUK SEC SCHOOL</option>
                <option value="TAIKOOPRIMARYSCHOOL">TAIKOO PRIMARY SCHOOL</option>
                <option value="TAKKEEPETROLEUMCOLTD">TAK KEE PETROLEUM CO LTD</option>
                <option value="TAKSUNSCHOOL">TAK SUN SCHOOL</option>
                <option value="TAXI-ASSOCIATIONCALLSERCTR">TAXI-ASSOCIATION CALL SER CTR</option>
                <option value="TECHNIX-PROMANAGEMENTEDUCEN">TECHNIX-PRO MANAGEMENT EDU CEN</option>
                <option value="TELECOMPAGING,DIGITAL&amp;amp;MANGOL">TELECOM PAGING,DIGITAL&amp;MANGO L</option>
                <option value="TENGDA(H.K.)COMPANYLIMITED">TENGDA(H.K.) COMPANY LIMITED</option>
                <option value="THECHINESEUNIVERSITYOFHK">THE CHINESE UNIVERSITY OF HK</option>
                <option value="THECOMMUNITYCATLINGNANU">THE COMMUNITY C AT LINGNAN U</option>
                <option value="THECORONATIONESTATESMGTLTD">THE CORONATION ESTATES MGT LTD</option>
                <option value="THEELCHKYLLUTHERANSECSCH">THE ELCHK YL LUTHERAN SEC SCH</option>
                <option value="THEGIRLS'BRIGADEHONGKONG">THE GIRLS' BRIGADE HONG KONG</option>
                <option value="THEGOODLUCKMOTORINGSCHLTD">THE GOOD LUCK MOTORING SCH LTD</option>
                <option value="THEHKACADEMYFORGIFTEDEDU">THE H K ACADEMY FOR GIFTED EDU</option>
                <option value="THEHKFEDERATIONOFINSURERS">THE H K FEDERATION OF INSURERS</option>
                <option value="THEHKFEDERATIONOFTRADEUN">THE H K FEDERATION OF TRADE UN</option>
                <option value="THEHKINSTITUTEOFHOUSING">THE H K INSTITUTE OF HOUSING</option>
                <option value="THEHERMITAGEESTATESMGTLTD">THE HERMITAGE ESTATES MGT LTD</option>
                <option value="THEHKACADFORPERFARTS">THE HK ACAD FOR PERF ARTS</option>
                <option value="THEHKACADEMYEDUCATIONALFL">THE HK ACADEMY EDUCATIONAL F L</option>
                <option value="THEHKINSTITUTEOFBANKERS">THE HK INSTITUTE OF BANKERS</option>
                <option value="THEHKINSTITUTEOFEDUCATION">THE HK INSTITUTE OF EDUCATION</option>
                <option value="THEHKMANAGASSOCIATION">THE HK MANAG ASSOCIATION</option>
                <option value="THEHKPOLYTECHNICUNIVERSITY">THE HK POLYTECHNIC UNIVERSITY</option>
                <option value="THEHKIEDJOCKEYCLUBPRISCH">THE HKIED JOCKEY CLUB PRI SCH</option>
                <option value="THEIOWNERSOFONEBEACONHILL">THE I OWNERS OF ONE BEACONHILL</option>
                <option value="THEIMCOFC&amp;amp;MACHUICHAKLAM">THE IMC OF C&amp;MA CHUI CHAK LAM</option>
                <option value="THEIMCOFELCHKLUTHERANSS">THE IMC OF ELCHK LUTHERAN S S</option>
                <option value="THEIMCOFFANLINGKAUYANCOL">THE IMC OF FANLING KAU YAN COL</option>
                <option value="THEIMCOFSHATINTSUNGTSINS">THE IMC OF SHATIN TSUNG TSIN S</option>
                <option value="THEINCMCOFPRECIOUSBLOOD">THE INC M C OF PRECIOUS BLOOD</option>
                <option value="THEJOCKEYCLUBEDUYOUNGCOLLE">THE JOCKEY CLUB EDUYOUNG COLLE</option>
                <option value="THELINK-CARPARK">THE LINK-CARPARK</option>
                <option value="THELINK-RETAIL">THE LINK-RETAIL</option>
                <option value="THEOPENUNIVERSITYOFHK">THE OPEN UNIVERSITY OF HK</option>
                <option value="THEREACHMANAGEMENTLIMITED">THE REACH MANAGEMENT LIMITED</option>
                <option value="THEUNIVERSITYOFHK">THE UNIVERSITY OF HK</option>
                <option value="TINKAPINGSECSCHOOL">TIN KA PING SEC SCHOOL</option>
                <option value="TINSHUIWAIMETHODISTCOLLEGE">TIN SHUI WAI METHODIST COLLEGE</option>
                <option value="TKTCATHOLICPRISCH(HOIFANR">TKT CATHOLIC PRI SCH(HOI FAN R</option>
                <option value="TNET.HK">TNET.HK</option>
                <option value="TOOLBOX">TOOLBOX</option>
                <option value="TOSHIBAHONGKONGLTD">TOSHIBA HONG KONG LTD</option>
                <option value="TOUCHTELECOMLIMITED">TOUCH TELECOM LIMITED</option>
                <option value="TRAFFICTICKETS(FIXEDPENALTY)">TRAFFIC TICKETS(FIXED PENALTY)</option>
                <option value="TRAVELEXPERTLIMITED">TRAVEL EXPERT LIMITED</option>
                <option value="TRAVELRESOURCESLIMITED">TRAVEL RESOURCES LIMITED</option>
                <option value="TREATS">TREATS</option>
                <option value="TRUELIGHTGIRLS'COLLEGE">TRUE LIGHT GIRLS' COLLEGE</option>
                <option value="TRUELIGHTMIDDLESCHOOLOFHK">TRUE LIGHT MIDDLE SCHOOL OF HK</option>
                <option value="TSANGMUIMILLENNIUMSCHOOL">TSANG MUI MILLENNIUM SCHOOL</option>
                <option value="TSUENWANCATHOLICPRIMARYSCH">TSUEN WAN CATHOLIC PRIMARY SCH</option>
                <option value="TSUNGTSINPRISCH&amp;amp;KINDERGAR">TSUNG TSIN PRI SCH &amp; KINDERGAR</option>
                <option value="TUCKSHOP">TUCK SHOP</option>
                <option value="TUNGWAHCOLLEGE">TUNG WAH COLLEGE</option>
                <option value="TUNGWAHGROUPOFHOSPITALS">TUNG WAH GROUP OF HOSPITALS</option>
                <option value="TUNGWAHGRPOFHLOKONTINGMC">TUNGWAH GRP OF H LOKONTING M C</option>
                <option value="TUNGWAHGRPOFHOSPITALS-RENT">TUNGWAHGRP OF HOSPITALS - RENT</option>
                <option value="TVBNETWORKVISION">TVB NETWORK VISION</option>
                <option value="UADMISSION">UADMISSION</option>
                <option value="UCNCOMMUNITYHEALTHSERVICE">UCN COMMUNITY HEALTH SERVICE</option>
                <option value="UNIHEART">UNIHEART</option>
                <option value="UNIONWELLDEVELOPMENTLIMITED">UNION WELL DEVELOPMENT LIMITED</option>
                <option value="UNITEDNATIONSREFUGEEAGENCY">UNITED NATIONS REFUGEE AGENCY</option>
                <option value="UNIVERSEPRINTINGCOLTD">UNIVERSE PRINTING CO LTD</option>
                <option value="URBANPROPERTYMANAGEMENTLTD">URBAN PROPERTY MANAGEMENT LTD</option>
                <option value="VALTORTACOLLEGE">VALTORTA COLLEGE</option>
                <option value="VINEBERGPROPMANAGLTD">VINEBERG PROP MANAG LTD</option>
                <option value="VITALANDSERVICESLIMITED">VITALAND SERVICES LIMITED</option>
                <option value="VITASOY">VITASOY</option>
                <option value="VOCATIONALTRAININGCOUNCIL">VOCATIONAL TRAINING COUNCIL</option>
                <option value="VTCSCHB&amp;amp;ISYSTEMS">VTC SCH B &amp; I SYSTEMS</option>
                <option value="WAICHOWPUBSCH(SHEUNGSHUI)">WAI CHOW PUB SCH (SHEUNG SHUI)</option>
                <option value="WALLSTREETENGLISH">WALL STREET ENGLISH</option>
                <option value="WATERSUPPLIESDEPARTMENT">WATER SUPPLIES DEPARTMENT</option>
                <option value="WATERFALL">WATERFALL</option>
                <option value="WATSON'SWATER">WATSON'S WATER</option>
                <option value="WEBSITESOLUTION">WEBSITE SOLUTION</option>
                <option value="WELLBORNREALESTATEMGTLTD">WELL BORN REAL ESTATE MGT LTD</option>
                <option value="WESTISLANDSCHOOL">WEST ISLAND SCHOOL</option>
                <option value="WHAMPOAGARDENMANAGEMENTLTD">WHAMPOA GARDEN MANAGEMENT LTD</option>
                <option value="WHAMPOAPM-CAMERONHOUSE">WHAMPOA P M - CAMERON HOUSE</option>
                <option value="WHAMPOAPM-RAMBLERCREST">WHAMPOA P M - RAMBLER CREST</option>
                <option value="WHAMPOAPM-HUNGHOMBAYCENTRE">WHAMPOA P M-HUNGHOM BAY CENTRE</option>
                <option value="WHAMPOAPM-PATTATINDBDG">WHAMPOA P M-PAT TAT IND BDG</option>
                <option value="WHAMPOAPM-PROVIDENTVILLAS">WHAMPOA P M-PROVIDENT VILLAS</option>
                <option value="WHAMPOAPROPMGTLTD-ABDCTR">WHAMPOA PROP MGT LTD-ABD CTR</option>
                <option value="WHARFT&amp;amp;TLIMITED">WHARF T&amp;T LIMITED</option>
                <option value="WILSONEXPRESS">WILSON EXPRESS</option>
                <option value="WILSONPARKING">WILSON PARKING</option>
                <option value="WINTINSWIMMINGCENTRELTD">WIN TIN SWIMMING CENTRE LTD</option>
                <option value="WINGONTRAVEL">WING ON TRAVEL</option>
                <option value="WKKTRAVELLIMITED">WKK TRAVEL LIMITED</option>
                <option value="WORLDVISIONHONGKONG">WORLD VISION HONG KONG</option>
                <option value="WORLDWIDEFUNDHK">WORLD WIDE FUND HK</option>
                <option value="YFHPETROPRODUCTS(HK)LTD">Y F H PETRO PRODUCTS (HK) LTD</option>
                <option value="YAHOO!HONGKONGLIMITED">YAHOO! HONG KONG LIMITED</option>
                <option value="YANCHAIHOSPITAL">YAN CHAI HOSPITAL</option>
                <option value="YANCHAIHOSPITALCTHWPS">YAN CHAI HOSPITAL C T H W P S</option>
                <option value="YANOITONG">YAN OI TONG</option>
                <option value="YANOITONGTINKAPINGPRISC">YAN OI TONG TIN KA PING PRI SC</option>
                <option value="YANGMEMMETHODISTSOCIALSVC">YANG MEM METHODIST SOCIAL SVC</option>
                <option value="YINGWACOLLEGE">YING WA COLLEGE</option>
                <option value="YINGWAPRIMARYSCHOOL">YING WA PRIMARY SCHOOL</option>
                <option value="YLCHAMBEROFCOMMPRISCHOOL">YL CHAMBER OF COMM PRI SCHOOL</option>
                <option value="YMTCATHOLICPRIS(HOIWANGRD)">YMT CATHOLIC PRI S (HOIWANGRD)</option>
                <option value="YORKINT'LCHILDCARECENTRE">YORK INT'L CHILD CARE CENTRE</option>
                <option value="YORKINT'LKDGN(CUMBERLANDR)">YORK INT'L KDGN (CUMBERLAND R)</option>
                <option value="YORKINT'LKDGN(ESSEXCRES)">YORK INT'L KDGN (ESSEX CRES)</option>
                <option value="YUCHUNKEUNGMEMORIALCOLLEGE">YU CHUN KEUNG MEMORIAL COLLEGE</option>
                <option value="YUENLONGCATHOLICSECSCHOOL">YUEN LONG CATHOLIC SEC SCHOOL</option>
                <option value="YUENLONGMERCHANTSASSOSECS">YUEN LONG MERCHANTS ASSO SEC S</option>
                <option value="ZONE1511">ZONE 1511</option>
                <option value="ZUELLIGPHARMALIMITED">ZUELLIG PHARMA LIMITED</option>
                <option value="ZURICHINSURANCE(HONGKONG)">ZURICH INSURANCE (HONG KONG)</option>
            </select>               
        </td>
        </tr>
        <tr class="LightGrey">
            <td class="label">Bill Account No.:</td>
            <td >
                <div style="width:50%">
                <input type="text" name="BillAcct" onkeypress="return disableEnterKey(event)" autocomplete="off" size="26" maxlength="25" value="">
                </div>
            </td>
        </tr>

<tr class="LightGrey">
    <td class="label">Bill Type:</td>
    <td >
        <select>
            <option>01 HOSTING</option>
            <option>02 WEB DESIGN</option>
            <option>03 E-SHOP</option>
            <option>04 OTHERS</option>
        </select>
    </td>
</tr>

<tr class="LightGrey">
    <td class="label">Amount:</td>
    <td >
            HKD&nbsp;
            <input type="text" name="PaymentAmt" autocomplete="off" size="16" maxlength="16"  value="">
    </td>
</tr>
<tr class="LightGrey">
    <td class="label">Deduct From Account:</td>
    <td ><font class="SELECT"> 
        <select name="targetDes" onfocus="setRegAcctRadioFocus()">
            <option value="" selected="selected">----------- Please select account -----------</option>
            <option value="0">$user_account[0].number $user_account[0].type</option>
            <option value="1">$user_account[1].number $user_account[1].type</option>
        </select>
        </font>
    </td>
</tr>
<tr class="LightGrey">
    <td >
    <input type="radio" name="WhenToPay" value="1" checked="checked">
    <font class="CONTENT">Transfer Now</font></td>
    <td ><font class="CONTENT">&nbsp;</font></td>
</tr>
<tr class="LightGrey">
    <td >
    <input type="radio" name="WhenToPay" value="0">
    <font class="CONTENT">Transfer Date</font></td>
    <td ><font class="SELECT"> 
    <select name="effDate" onfocus="">
        <option value="21-11-2014">21-11-2014</option>
        <option value="22-11-2014">22-11-2014</option>
        <option value="24-11-2014">24-11-2014</option>
        <option value="25-11-2014">25-11-2014</option>
        <option value="26-11-2014">26-11-2014</option>
        <option value="27-11-2014">27-11-2014</option>
        <option value="28-11-2014">28-11-2014</option>
        <option value="29-11-2014">29-11-2014</option>
        <option value="01-12-2014">01-12-2014</option>
        <option value="02-12-2014">02-12-2014</option>
        <option value="03-12-2014">03-12-2014</option>
        <option value="04-12-2014">04-12-2014</option>
        <option value="05-12-2014">05-12-2014</option>
        <option value="06-12-2014">06-12-2014</option>
        <option value="08-12-2014">08-12-2014</option>
        <option value="09-12-2014">09-12-2014</option>
        <option value="10-12-2014">10-12-2014</option>
        <option value="11-12-2014">11-12-2014</option>
        <option value="12-12-2014">12-12-2014</option>
        <option value="13-12-2014">13-12-2014</option>
        <option value="15-12-2014">15-12-2014</option>
        <option value="16-12-2014">16-12-2014</option>
        <option value="17-12-2014">17-12-2014</option>
        <option value="18-12-2014">18-12-2014</option>
        <option value="19-12-2014">19-12-2014</option>
        <option value="20-12-2014">20-12-2014</option>
        <option value="22-12-2014">22-12-2014</option>
        <option value="23-12-2014">23-12-2014</option>
        <option value="24-12-2014">24-12-2014</option>
        <option value="27-12-2014">27-12-2014</option>
        <option value="29-12-2014">29-12-2014</option>
        <option value="30-12-2014">30-12-2014</option>
        <option value="31-12-2014">31-12-2014</option>
    </select>
    </font></td>
</tr> 
<tr class="LightGrey">
    <td></td>
    <td>
        <input type="submit" name="payBill" value="Submit Bill Payment"/>
    </td>
</tr>
</tbody>
</table>
</form>
</div>
<!-- importantNotes -->
<div id="importantNotes" class="noMarginBottom">
    <h3>Note:</h3>
    <ol>    
        <li>Once an instant payment instruction is submitted, no amendment or cancellation is allowed, regardless of the instruction's processing status.</li>
        <li>To avoid any penalty fees  to be charged  by your merchant (if applicable) , you are suggested to pay the bill 1-2 working days before the due date that is shown on the e-bill.</li>
        <li>For online bill payment with credit card, the payment must be used to settle wholly or partially an underlying genuine debt due to the payee (the "Debt"). The Cardholder is required to provide evidence
        thereof if so requested by First Bank. Hang Seng reserves the right to decline generating Cash Dollars, or to cancel the Cash Dollars generated, for any payment which Hang Seng suspects not be used to settle
        the Debt. 
        </li>
    </ol>
</div> <!--/ importantNotes -->
        </div> <!--/ content middle -->
        <div id="contentBox-bottom"></div>
</div>